const nome = 'Wescley';
const sobrenome = 'Vieira';
const idade = 25;
const peso = 61;
const altura = 1.70;
let imc;
let anoNascimento;
imc = peso/(altura*altura);
anoNascimento = 2022-idade;
console.log(`${nome} ${sobrenome} tem ${idade} anos pesa ${peso} Kg`);
console.log(`tem ${altura} de altura e seu IMC é de ${imc}`);
console.log(`${nome} nasceu em ${anoNascimento}`);